Open readme when the project opens in vscode
sander1095/vscode-readme-auto-open pull request #12
Opened 2024-10-04 09:45 UTC by Ahrjen

This pull request includes changes to improve the functionality and activation of the `readme-auto-open` extension. The key changes involve modifying the activation events and enhancing the logic to automatically open the `readme.md` file if it exists in the workspace.

### Improvements to extension activation:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L12-R17): Added an activation event to trigger the extension when a `readme.md` file is detected in the workspace. Removed the predefined command from the `commands` section.

### Enhancements to extension functionality:

* [`src/extension.ts`](diffhunk://#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626L1-R30): Simplified the activation log message and added logic to check for the existence of `readme.md` files in various capitalizations. If a `readme.md` file is found, it is opened automatically, and a flag is set to indicate that the user has seen the readme.

Resolves #5

2024-10-04 14:41 UTC, sander1095 requested changes

2024-10-04 14:41 UTC, sander1095 commented on src/extension.ts
> +        const readmePatterns = ['readme.md', 'README.md', 'Readme.md'];
Dan kan de foreach hieronder er ook uit en moet die code aangepast worden :)

2024-10-04 14:41 UTC, sander1095 commented on src/extension.ts
> +                    vscode.window.showTextDocument(readmePath);
volgens de docs is dit async-awaitable :) 

https://code.visualstudio.com/api/extension-guides/virtual-documents

2024-10-04 14:41 UTC, sander1095 commented on src/extension.ts
> +        const readmePatterns = ['readme.md', 'README.md', 'Readme.md'];
Dan kun je logging waarin een harde `readme.md` staat, ook vervangen met `README` oid..

2024-10-06 09:39 UTC, Ahrjen commented on package.json
> +    "workspaceContains:readme.md"
Wel voor de .md's. ik vermoed dat .txt niet gezien wordt. In de package.json is de bestandsnaam niet hoofdlettergevoelig (getest) maar in de extension.ts wel

2024-10-06 12:52 UTC, Ahrjen commented
**Implemented**
- async await
- readme.*
- use built-in findFiles instead of forEach
- Better logging

**Tested**
- 1 workspace folder (readme is opened once)
- 1 workspace with multiple workspace folders (any readme in workspace folder roots are opened once)
- Empty workspace (no errors thrown, activationEvent does not find a readme, so extension.ts is not executed)
- 1 file in empty workspace (no errors thrown, activationEvent does not find a readme, so extension.ts is not executed)

2024-10-06 13:09 UTC, sander1095 commented on package.json
> +    "workspaceContains:readme.md"
In dat geval is het wel even goed om te testen dat het werkt in alle scenario's, want dat is wel de bedoeling :D 

Volgens de docs kun je er een `glob pattern` van maken: https://code.visualstudio.com/api/references/activation-events#workspaceContains

Zou je dit willen testen?

```
workspaceContains:[rR][eE][aA][dD][mM][eE]*.*
```

2024-10-06 14:18 UTC, Ahrjen commented on package.json
> +    "workspaceContains:readme.md"
Jep, die heb ik al veranderd in de laatste commits

2024-11-22 10:38 UTC, closed without merging